version: 2

models:
  # Campagne_Marketing ------------------------------------------------------------------------------------
  
  # Clients -----------------------------------------------------------------------------------------------
  - name: Clients
    description: Table des clients nettoyée. Les produits des favoris des clients ne sont pas normalisés 
    columns: 
      - name: id_client
        description: Clé Primaire. Pas de test 'not_null', les clients n'ayant pas d'id sont automatiquement supprimés
        test: 
          - unique
      - name: prenom
        description: Prenom du client avec premiere lettre en majuscule ou NULL
      - name: nom
        description: Nom de famille du client avec premiere lettre en majuscule ou NULL
      - name: email
        description: Email du client valide ou NULL
      - name: age
        description: Age du client (int). Chiffre superieur a 0 ou NULL
        tests:
        - dbt_utils.expression_is_true:
            expression: '< 110'
            config:
              severity: warn
      - name: genre
        description: Genre du client. 'Homme', 'Femme' ou NULL
      - name: frequence_visites
        description: Nombre de visites (int) du client sur le site. Chiffre superieur a 0 ou NULL
      - name: telephone
        description: Numero de téléphone au format '+XXX-XXX-XXX-XXXX' ou NULL
      - name: date_inscription
        description: Date d'inscription (date) du client ou NULL. Avant la date d'aujourd'hui
      - name: favoris
        description: Liste de produits favoris, séparé par des vigules ou NULL. A traiter dans Constellation
      - name: ip
        description: Adresse IPv4 du client ou NULL. Au format 'XXX.XXX.XXX.XXX'
        
  # Commandes ---------------------------------------------------------------------------------------------
  - name: Commandes
    columns:
      - name: id_commande
        tests:
          - not_null
          - unique
      - name: id_client
      - name: id_entrepot_depart
      - name: date_commande
      - name: id_promotion_appliquee
      - name: mode_de_paiement
      - name: numero_tracking
      - name: date_livraison_estimee

  # Details_Commandes -------------------------------------------------------------------------------------
  - name: Details_commandes
    columns:
      - name: id_commande
        tests:
          - not_null
          - unique
          
  # Entrepots ---------------------------------------------------------------------------------------------

  # Entrepots_Machines ------------------------------------------------------------------------------------

  # Posts -------------------------------------------------------------------------------------------------

  # Produits ----------------------------------------------------------------------------------------------

  # Promotions --------------------------------------------------------------------------------------------
  - name: Promotions
    columns:
      - name: id_promotion
        tests:
          - not_null
          - unique
      - name: id_produit
        tests:
          - not_null
          - relationships:
              to: ref('Produits')
              field: id_produit
      - name: type_promotion
        description: soit 'Pourcentage' soit 'Remise fixe'
        tests:
          - not_null
          - accepted_values:
              values: ['Pourcentage', 'Remise fixe']
      - name: valeur_promotion
        description: en euro
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type: # Hugues : Pour tester le type d'une colone il manquait le paquet dbt_expectations. Je l'ai installé, cf packages.yml
              column_type : NUMERIC
              config: # Hugues : apparement il y a une ligne qui contient une valeur non numerique. Configuré pour avertir seulement et pas bloquer completement le build, a verifier.
                severity: warn
      - name: date_debut
        description: Date de début de la promotion 'yyyy-mm-dd'
        tests:
          - not_null
      - name: date_fin
        description: Date de fin de la promotion 'yyyy-mm-dd'
        tests:
          - not_null
          #- dbt_utils.expression_is_true:          # Hugues : Je vois ce que tu veux faire, mais peut-etre le mieux ce serait de supprimer la ligne dans le modele si ce cas se produit.
          #    expression: "date_fin >= date_debut" # Si tu veux absollument faire ce test c'est compliqué, bonne chance !...
      - name: responsable_promotion                 
        description: title de la responsable, ex., 'Responsable Marketing'
        tests:
          - not_null

  # Satisfaction ------------------------------------------------------------------------------------------
  - name: Satisfaction
    columns:
      - name: id_satisfaction
        tests:
          - not_null
          - unique
    



          




