version: 2

sources:
  - name: google_drive
    tables:
      - name: carttrend_campaigns_campagnes
      - name: carttrend_clients_clients
      - name: carttrend_commandes_commandes
      - name: carttrend_details_commandes_details_commandes_
      - name: carttrend_entrepots_entrepots
      - name: carttrend_entrepots_machines_machines_entrepots
      - name: carttrend_posts_posts
      - name: carttrend_produits_produits
      - name: carttrend_promotions_promotions
      - name: carttrend_satisfaction_satisfaction